/**
 * ZAPIER "Code by Zapier" STEP — Run Javascript
 * Step: "Commit Template to GitHub"
 *
 * Takes the HTML generated by the previous ("Generate HTML Template via Claude
 * API") step and creates/updates a file in the user's GitHub repo via the
 * Contents API, then returns links for the confirmation email.
 *
 * MANUAL CONFIGURATION REQUIRED (Zapier step editor):
 *   1. Input Data field `html`            -> map to step 2 output `html`.
 *   2. Input Data field `githubToken`     -> map to the validated step-1 output
 *      (which came from the GHL payload) OR, for a lower-risk setup, map to a
 *      per-user token stored once in Storage by Zapier during onboarding
 *      instead of accepting a raw PAT through the chatbot on every request.
 *   3. Input Data fields `githubOwner`, `githubRepo`, `githubBranch`,
 *      `templateDescription` -> map from step 1 output.
 *
 * REQUIRED TOKEN SCOPES
 *   - Fine-grained PAT: Contents: Read and write, scoped to the single target repo.
 *   - Classic PAT (legacy): `repo` scope.
 *
 * SECURITY
 *   - The token is only read from `inputData.githubToken`, used in the
 *     Authorization header, and never included in `output` or log lines.
 */

const GITHUB_API = 'https://api.github.com';
const FILE_DIR = 'templates';
const REQUEST_TIMEOUT_MS = 30000;

/** Validates required inputs and normalizes optional ones. */
function validateInput(inputData) {
  const required = ['html', 'githubToken', 'githubOwner', 'githubRepo'];
  const missing = required.filter((key) => !inputData[key]);

  if (missing.length) {
    throw new Error(`VALIDATION_FAILED: missing required field(s): ${missing.join(', ')}`);
  }

  const token = inputData.githubToken.toString().trim();
  if (!/^(ghp_|github_pat_|gho_)/.test(token)) {
    throw new Error('VALIDATION_FAILED: githubToken does not look like a valid GitHub token.');
  }

  return {
    html: inputData.html.toString(),
    githubToken: token,
    githubOwner: inputData.githubOwner.toString().trim(),
    githubRepo: inputData.githubRepo.toString().trim().replace(/\.git$/, ''),
    githubBranch: (inputData.githubBranch || 'main').toString().trim(),
    templateDescription: (inputData.templateDescription || 'template').toString().trim(),
  };
}

/** Turns a free-text description into a safe, URL-friendly filename slug. */
function slugify(text) {
  const slug = text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);

  return slug || 'template';
}

/** Builds `templates/<slug>-<timestamp>.html`, guaranteeing uniqueness per run. */
function buildFilePath(templateDescription) {
  const slug = slugify(templateDescription);
  const timestamp = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14); // YYYYMMDDHHmmss
  return `${FILE_DIR}/${slug}-${timestamp}.html`;
}

/** Base64-encodes UTF-8 text for the Contents API (works in Zapier's Node runtime). */
function toBase64(text) {
  return Buffer.from(text, 'utf-8').toString('base64');
}

function authHeaders(token) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'User-Agent': 'ai-website-template-generator-zap',
  };
}

/**
 * Looks up an existing file's SHA (needed for updates). Returns null if the
 * file doesn't exist yet — that's the expected case for a brand-new template.
 */
async function getExistingFileSha({ githubOwner, githubRepo, githubBranch, filePath, githubToken }) {
  const url = `${GITHUB_API}/repos/${githubOwner}/${githubRepo}/contents/${filePath}?ref=${githubBranch}`;

  const response = await z.request({
    url,
    method: 'GET',
    headers: authHeaders(githubToken),
    timeout: REQUEST_TIMEOUT_MS,
    skipThrowForStatus: true,
  });

  if (response.status === 200) {
    return response.json().sha;
  }
  if (response.status === 404) {
    return null;
  }

  throw new Error(`GITHUB_LOOKUP_FAILED: HTTP ${response.status} — ${(response.content || '').slice(0, 300)}`);
}

/** Creates or updates the file via PUT /repos/{owner}/{repo}/contents/{path}. */
async function putFile({ githubOwner, githubRepo, githubBranch, filePath, html, githubToken, templateDescription, existingSha }) {
  const url = `${GITHUB_API}/repos/${githubOwner}/${githubRepo}/contents/${filePath}`;

  const body = {
    message: `Add AI-generated template: ${templateDescription.slice(0, 72)}`,
    content: toBase64(html),
    branch: githubBranch,
  };
  if (existingSha) {
    body.sha = existingSha;
  }

  const response = await z.request({
    url,
    method: 'PUT',
    headers: authHeaders(githubToken),
    body,
    timeout: REQUEST_TIMEOUT_MS,
    skipThrowForStatus: true,
  });

  return response;
}

/** Maps common GitHub error statuses to clear, user-facing error messages. */
function handleErrorStatus(status, bodyText) {
  if (status === 401) {
    throw new Error('GITHUB_AUTH_FAILED: token is invalid, expired, or lacks access to this repo.');
  }
  if (status === 403) {
    throw new Error(`GITHUB_FORBIDDEN: token lacks required scopes (repo / contents:write), or rate-limited — ${bodyText.slice(0, 200)}`);
  }
  if (status === 404) {
    throw new Error('GITHUB_REPO_NOT_FOUND: check that owner/repo/branch are correct and the token can see this repo.');
  }
  throw new Error(`GITHUB_COMMIT_FAILED: HTTP ${status} — ${bodyText.slice(0, 300)}`);
}

// ---- Main entry point -----------------------------------------------------

const validated = validateInput(inputData);
const filePath = buildFilePath(validated.templateDescription);

z.console.log(`[github] committing to ${validated.githubOwner}/${validated.githubRepo}@${validated.githubBranch}:${filePath}`);

const existingSha = await getExistingFileSha({ ...validated, filePath });

let response = await putFile({ ...validated, filePath, existingSha });

// Handle a rare race where the file was created between our GET and PUT
// (409/422 with an sha mismatch) by re-fetching the sha once and retrying.
if ((response.status === 409 || response.status === 422) && !existingSha) {
  z.console.log('[github] sha conflict on first attempt, refetching and retrying once');
  const retrySha = await getExistingFileSha({ ...validated, filePath });
  response = await putFile({ ...validated, filePath, existingSha: retrySha });
}

if (response.status !== 200 && response.status !== 201) {
  handleErrorStatus(response.status, response.content || '');
}

const result = response.json();

const output = {
  filePath,
  commitSha: result.commit.sha,
  commitUrl: result.commit.html_url,
  fileUrl: result.content.html_url,
  rawUrl: `https://raw.githubusercontent.com/${validated.githubOwner}/${validated.githubRepo}/${validated.githubBranch}/${filePath}`,
};

z.console.log(`[github] success — commit ${output.commitSha}`);

return output;
